### ISSUE TITLE
Object Explorer improvements

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#10537]
## TODO:

- [x] Make columns resizable
- [x] Set same font used in the Variable Explorer
- [x] Don't expand rows of collections (list, set, dict, numpy arrays, etc.).
- [x] Remove `repr` preview
- [x] Open editor by clicking in any cell of the row (not only value)

As discussed with @ccordoba12
