### ISSUE TITLE
Debugging improvements

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#10538]
## TODO:

- [x] ~~Enable/disable actions on the toolbar menu depending on the debugging state (if not debugging, only the 'start debugging' action should be enable, while debugging the 'start debugging' action should be disable).~~ This will be added when the look of disabled buttons in QDarkStyle improves.
- [x] Update Editor debugger panel taking into account the current console.
- [x] Check that debugging files are open

As discussed with @ccordoba12

**Comment by gb119** [comment]
I was going to file a separate feature request, but I think it belongs here and I don think it's a duplicate:

### Change the Debug arrow to reflect current debug state

The editor pane shows the current line arrow when code is run under the debugger, but if the user has continued running the code (or is running to the return point) then there is no indication of this. It would be nice if the arrow could change appearance to reflect whether the dubber was executing code or waiting at the indicated line for user input. (e.g. changing from right arrow to down chevrons/ down play/pause glyph).
