### ISSUE TITLE
Spyder4 hangs on the running turtle module

### ISSUE THREAD

**Issue by w1593950** [spyder-ide/spyder#11124]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

For some reason, spyder4 hangs on the running turtle module. 

I'm trying to use the turtle module to teach my 8 and 10 years old kids gaming and programming using Spyder ( I'm a big fanatic of Spyder and my kids wants to use too. ) 

Recently I upgrade to Spyder4 from Spyder3. I noticed wired hanging state when I run/execute the program. 

Attached the program/source code. Please download it and test it and execute it. I dont know where I'm doing the mistake or whats the error. 

### What steps reproduce the problem?

1. Down the attached file and execute/run the file in spyder4 ide

### What is the expected output? What do you see instead?

When the program exited, it should completely closed and exited. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.0.0.
* Python version: 3.8.0
* Qt version:  
* PyQt version: 
* Operating System name/version:  macOS 10.15

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by w1593950** [comment]
```# Falling Skies in Python for Beginners
# Part 1 : Getting Started --- Setting up Screen
# Part 2 : Adding the deer
# Part 3 : Moving the deer
# Part 4 : nuts falling and collisions

import turtle
import random

wn = turtle.Screen()
wn.title("Falling Skies")
wn.bgcolor("light green")
wn.setup(width=800, height=600)
wn.tracer(0)


# Add the deer
deer = turtle.Turtle()
deer.speed(0)
deer.shape("square")
deer.color("white")
deer.penup()
deer.goto(0, -250)
deer.direction = "stop"

# Add the nut
nut = turtle.Turtle()
nut.speed(0)
nut.shape("circle")
nut.color("blue")
nut.penup()
nut.goto(0, 250)


# Functions
def go_left():
    deer.direction = "left"

def go_right():
    deer.direction = "right"


# Keyboard Bindings
wn.listen()
wn.onkeypress(go_left, "Left")
wn.onkeypress(go_right, "Right")

# Main game loop
while True:
    # Update screen
    wn.update()

    # Move the deer
    if deer.direction == "left":
        x = deer.xcor()
        x -= 3
        deer.setx(x)

    if deer.direction == "right":
        x = deer.xcor()
        x += 3
        deer.setx(x)

    # Move the nut
    y = nut.ycor()
    y -= 3
    nut.sety(y)

    # Check if off the screen
    if y < -300:
        x = random.randint(-380, 380)
        y = random.randint(300, 400)
        nut.goto(x, y)

    # check for a collison with the deer
    if nut.distance(deer) < 20:
        x = random.randint(-380, 380)
        y = random.randint(300, 400)
        nut.goto(0, 250)


wn.mainloop()

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @w1593950 sorry for the late response, maybe you could try some of the elements listed [here](https://github.com/spyder-ide/spyder/wiki/How-to-run-turtle-scripts-within-Spyder).

If you prefer to left the code unchanged you can use the `Execute in an external system terminal` option under (`Run > Configuration per file...` accessible also with `Ctrl+F6`). Testing with this option I'm always capable of running the script and also I can see a traceback when closing the window (however for each run you probably will need to close the terminal that shows the traceback): 

```traceback
Traceback (most recent call last):
  File "C:\Users\Daniel\.spyder-py3\temp.py", line 56, in <module>
    deer.setx(x)
  File "C:\Users\Daniel\Anaconda3\envs\4v\lib\turtle.py", line 1808, in setx
    self._goto(Vec2D(x, self._position[1]))
  File "C:\Users\Daniel\Anaconda3\envs\4v\lib\turtle.py", line 3158, in _goto
    screen._pointlist(self.currentLineItem),
  File "C:\Users\Daniel\Anaconda3\envs\4v\lib\turtle.py", line 755, in _pointlist
    cl = self.cv.coords(item)
  File "<string>", line 1, in coords
  File "C:\Users\Daniel\Anaconda3\envs\4v\lib\tkinter\__init__.py", line 2469, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
```
Another approach could be adding some `try-except` statements to the original script (which enabled me to do multiple runs of the script using the IPython Console):

```python
# Part 1 : Getting Started --- Setting up Screen
# Part 2 : Adding the deer
# Part 3 : Moving the deer
# Part 4 : nuts falling and collisions

import turtle
import random

wn = turtle.Screen()
wn.title("Falling Skies")
wn.bgcolor("light green")
wn.setup(width=800, height=600)
wn.tracer(0)


# Add the deer
deer = turtle.Turtle()
deer.speed(0)
deer.shape("square")
deer.color("white")
deer.penup()
deer.goto(0, -250)
deer.direction = "stop"

# Add the nut
nut = turtle.Turtle()
nut.speed(0)
nut.shape("circle")
nut.color("blue")
nut.penup()
nut.goto(0, 250)


# Functions
def go_left():
    deer.direction = "left"

def go_right():
    deer.direction = "right"


# Keyboard Bindings
wn.listen()
wn.onkeypress(go_left, "Left")
wn.onkeypress(go_right, "Right")

# Main game loop
while True:
    try:
        # Update screen
        wn.update()
    
        # Move the deer
        if deer.direction == "left":
            x = deer.xcor()
            x -= 3
            deer.setx(x)
    
        if deer.direction == "right":
            x = deer.xcor()
            x += 3
            deer.setx(x)
    
        # Move the nut
        y = nut.ycor()
        y -= 3
        nut.sety(y)
    
        # Check if off the screen
        if y < -300:
            x = random.randint(-380, 380)
            y = random.randint(300, 400)
            nut.goto(x, y)
    
        # check for a collison with the deer
        if nut.distance(deer) < 20:
            x = random.randint(-380, 380)
            y = random.randint(300, 400)
            nut.goto(0, 250)
    except:
        break
try:
    turtle.done()
except turtle.Terminator:
    pass

``` 
Hope this helps you to continue teaching your kids using Spyder! :)

**Comment by ccordoba12** [comment]
Closing because I think @dalthviz's answer is enough.
