### ISSUE TITLE
Pending API work

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#13527]
The text in parens gives an idea of effort (small, medium, big, etc). Issues related to the issue ara attached as well as PRs (if open already).

### Find in Files

- [x] **(small)** Fix issues. [Issue 13657](https://github.com/spyder-ide/spyder/issues/13657) ([PR 13675](https://github.com/spyder-ide/spyder/pull/13675))

### Profiler Pane

- [x] **(small)** Fix issues. [Issue 13698](https://github.com/spyder-ide/spyder/issues/13698)

### Layout plugin

- [x] **(medium)** Create a new Plugin using new API. ([PR 13479](https://github.com/spyder-ide/spyder/pull/13479))
- [x] **(medium)** Fix layout when opening 4.x -> master. [Issue 13629](https://github.com/spyder-ide/spyder/issues/13629) ([PR 13479](https://github.com/spyder-ide/spyder/pull/13479))

### IPython Plugin

- [x] **(medium)** Move to new plugin. [Issue 12194](https://github.com/spyder-ide/spyder/issues/12194) ([PR 12749](https://github.com/spyder-ide/spyder/pull/12749))

### Variable Explorer Plugin

- [x] **(medium)** Move to new API. [Issue 12184](https://github.com/spyder-ide/spyder/issues/12184) ([PR 12161](https://github.com/spyder-ide/spyder/pull/12161))

### Pylint plugin

- [x] **(medium)** Move to new API. [Issue 12183](https://github.com/spyder-ide/spyder/issues/12183) ([PR 12160](https://github.com/spyder-ide/spyder/pull/12160))

### Completion plugins

- [x] **(big)** Move to new API. [Issue 11744](https://github.com/spyder-ide/spyder/issues/11744), [Issue 12192](https://github.com/spyder-ide/spyder/issues/12192) ([PR 12969](https://github.com/spyder-ide/spyder/pull/12969))

### API Docs.

- [ ] **(big)** https://github.com/spyder-ide/spyder-api-docs

### New Cookiecutter

- [x] **(medium)** https://github.com/spyder-ide/spyder5-plugin-cookiecutter

### Main Interpreter plugin

- [x] **(medium)**. Move to new API. [Issue 13103](https://github.com/spyder-ide/spyder/issues/13103) ([PR 13104](https://github.com/spyder-ide/spyder/pull/13104))

### Toolbar plugin

- [x] **(small)** Create new plugin. ([PR 13547](https://github.com/spyder-ide/spyder/pull/13547))

### Explorer plugin

- [x] **(medium)**. Move to new API. [Issue 12195](https://github.com/spyder-ide/spyder/issues/12195)

### Main Menu

- [x] **(medium)** Create new Plugin. ([PR 13542](https://github.com/spyder-ide/spyder/pull/13542))

### Editor plugin

- [x] **(small)** Move editor API back to editor ([PR 13436](https://github.com/spyder-ide/spyder/pull/13436))
- [ ] **(Very big)** Move to new API. [Issue 12193](https://github.com/spyder-ide/spyder/issues/12193)

### Shortcuts

- [x] **(small)** Move all Shortcut methods to the shortcut plugin (See `config`  and `mainwindow`)
- [ ] **(small)** Add the following shortcuts:
  - console clear line
  - console clear shell
  - console inspect current object
- [ ] **(small)** Make the shortcuts use the defined actions from the new API so the names are localizable.

### Spyder-kernel

- [ ] **(small)** Move IO plugins to spyder-kernel, remove plugins from Spyder. [Issue 12761](https://github.com/spyder-ide/spyder/issues/12761)

### Tour

- [x] **(small-medium)** Move to plugin. [PR 14276](https://github.com/spyder-ide/spyder/pull/14276)

### Arrray Builder

- [ ] **(small)** Move to plugin. Editor and Console can optionally depend on it.

### Find/replace

- [ ] **(small)**. Move to plugin. Editor, Console, Help, Variable Explorer can optionally depend on it. Variable explorer could also use it to create a new small Array directly. Other plugins could use it or extend it with language specific syntax.

### Completion Widget

- [ ] **(small)** Move the completion widget to the plugin in charge of completions. (The Completion Manager plugin). [Issue 12976](https://github.com/spyder-ide/spyder/issues/12976)

### Preferences

- [ ] **(medium)** Remove special-case Preferences (with access to main window) and use a single type of PluginPreferenceConfigPage
- [ ] **(small)** Send changed options to other plugins, so plugins can react to changes, instead of applying changes to other plugins from within the config page. 

### Other

- [ ] **(small)** Add test to check dependencies correspond with REQUIRES. ([PR 13437](https://github.com/spyder-ide/spyder/pull/13437))
- [ ] **(small)** Go over `TODO: ` related to API work and fix them.
- [ ] **(small)** Add API for adding user-defined highlight patters (file, uri are examples of these) [Issue 9573](https://github.com/spyder-ide/spyder/issues/9573)
- [ ] **(small-medium)** Add API to extend and overload actions. [Issue 12859](https://github.com/spyder-ide/spyder/issues/12859) ([PR 12784](https://github.com/spyder-ide/spyder/pull/12784))
- [ ] **(small)** Load/Hide plugins on startup based on state on close. [Issue 13067](https://github.com/spyder-ide/spyder/issues/13067)
- [ ] **(small)**. Add dependency injection for register method. [Issue 13285](https://github.com/spyder-ide/spyder/issues/13285)

### Core plugin

- [x] **(medium)** A plugin in charge of adding Core Spyder features that are application-wide and do not fit on another plugin. [Issue 12789](https://github.com/spyder-ide/spyder/issues/12789)

### Python plugin

- [ ] **(medium)** Move Python specific functionality to a specific plugin. [Issue 12531](https://github.com/spyder-ide/spyder/issues/12531)

**Comment by ccordoba12** [comment]
Closing because this is quite old now.
