### ISSUE TITLE
Minor update to standalone, conda-based installation via conda breaks the application

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#21640]
The current conda-based installer builds a Spyder conda package from a modified feedstock to accommodate creating the application shortcut with `menuinst`. When updating the conda-based installer using `conda install`, a Spyder conda package built from the standard feedstock is retrieved and clobbers the `Menu` directory resulting in a broken application.

### Proposal

1. The installer will create an empty file and `is_conda_based_app` will check for this file to determine whether Spyder is a conda-based app. This ensures the distinction even if a standard conda package installs `spyder-menu.json`. This step can be done immediately without consequence.
2. The standard feedstock will be updated with the `spyder-menu.json` that is currently used in the installer builds. This should not affect standard conda installations.
3. After the standard feedstock is updated, the installer build will no longer need to patch it.

This proposal means that all Spyder conda packages (on feedstock dev branch) will include the `spyder-menu.json` and will be safe to install in both standard conda environments as well as our conda-based installer runtime environments. It also guarantees correct distinction of a conda-based application environment because it will rely on a feature that _only_ the installer creates.

* [x] conda-forge/spyder-feedstock#154
* [x] conda-forge/spyder-feedstock#155
* [x] conda-forge/spyder-feedstock#156
* [x] conda-forge/spyder-feedstock#158
* [x] ~~#21646~~ 
* [ ] #21647

**Comment by mrclary** [comment]
@ccordoba12 @dalthviz @jaimergp,
I discovered that for `conda>=23.11.0`, `menuinst>=2.0` is also installed. Because the update to Spyder's feedstock now includes the updated menu file, this means that an end user will automatically create an application shortcut/bundle upon installing Spyder in any conda environment. This may not be what we want.

I have some ideas about how to fix this, but I think we should first decide exactly what UX we want, i.e. under which circumstances an application shortcut/bundle should be created.
1. Created _only_ for our installer environment, and done so automatically.
1. Can be created for any environment: automatically for our installer environment, but deliberate action(s) are required by the user for a standard conda environment.
1. Created automatically for any environment.

I assume we prefer the first option (my preference). Thoughts?

**Comment by jaimergp** [comment]
What we did for napari was to ship the menu file in a different output (napari-menu) that depends on napari. Then, the "opt-in" action is via adding that optional package to your environment. We opt everyone in in the installers by adding napari-menu to the list. Would that work for your use case?

**Comment by mrclary** [comment]
> What we did for napari was to ship the menu file in a different output (napari-menu) that depends on napari. Then, the "opt-in" action is via adding that optional package to your environment. We opt everyone in in the installers by adding napari-menu to the list. Would that work for your use case?

This is exactly what I had in mind, or some variation of it, inspired by napari.

The PRs listed in the OP would result in UX option 3. I'm confident that we don't want this option, so the choice is really between UX option 1 and 2.

Imitating napari would result in UX option 2. Publishing a `spyder-menu` package to conda-forge simultaneously with `spyder` would make it easiest for a user to opt in to creating the application shortcut/bundle. Alternatively, if we want to discourage shortcuts/bundles outside of our installer environment, we could publish a `spyder-menu` package to a separate label (e.g. `conda/label/spyder_menu`) in order to make it harder for a user to opt in for an arbitrary conda environment.

For UX option 1, we would only create a `spyder-menu` package locally at installer build time, include it in the installer, but not publish it to conda-forge. This would effectively reserve the shortcut/bundle for our installer environment and prevent users from creating it in an arbitrary environment.

There are a few reasons why we may consider UX option 1.
* One of the principle reasons for creating our installer is to steer users toward an isolated runtime environment for Spyder; UX option 2 may undermine that effort.[1]
* Having a single shortcut/bundle would be less confusing to users (particularly new users). Multiple shortcuts/bundles for the same application requires name mangling (e.g. Spyder-ver-env.app) which is not a common practice. Are there UX standards/guidelines that say anything about this?

[1] The `app` section of the `meta.yaml` file for building the conda package can take the option `own_environment: True` (see [here](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#own-environment)). This should result in Spyder being installed into its own environment _when installed through Anaconda Navigator_. This could be a good compliment to our installer.

**Comment by ccordoba12** [comment]
> this means that an end user will automatically create an application shortcut/bundle upon installing Spyder in any conda environment. This may not be what we want.

Why not? That would improve how Spyder works on Mac and Linux when installed in conda envs. Furthermore, that's how Spyder has been working on Windows for a long time, so we need to preserve that.

> I think we should first decide exactly what UX we want, i.e. under which circumstances an application shortcut/bundle should be created

Is it possible to add the shortcut to a different folder than the default `Anaconda` one on Windows? Besides doing that, I think we should rename it to `Spyder (application)` to distinguish it from the env shortcuts.

**Comment by mrclary** [comment]
> > this means that an end user will automatically create an application shortcut/bundle upon installing Spyder in any conda environment. This may not be what we want.
> 
> Why not? That would improve how Spyder works on Mac and Linux when installed in conda envs. Furthermore, that's how Spyder has been working on Windows for a long time, so we need to preserve that.

I agree that automatically creating the shortcut will make a more desirable UX for standard conda environments; I just wonder if that will discourage adopting our installers which ensure that Spyder has an isolated runtime environment. I did not realize that `menuinst` was installed into base environments by default on Windows; this is currently not the case for macOS and Linux. Although given the update to `menuinst`, it may be included in base environments by default in the future. I'm not necessarily opposed to it, but I think we should decide whether or not to automatically create a shortcut in any environment because it is the _best_ UX, not just because we've been doing it on Windows for a long time.

> Is it possible to add the shortcut to a different folder than the default `Anaconda` one on Windows? 

I don't think so. The shortcut location is placed in the standard location for each platform.

> Besides doing that, I think we should rename it to `Spyder (application)` to distinguish it from the env shortcuts.

This, of course, is not necessary if we reserve the shortcut for just our installer. However, if the shortcut is created automatically for any environment, then we will need to settle on a general and scalable naming scheme using environment variables available to `menuinst` at package creation time and/or at package install time. (See https://conda.github.io/menuinst/reference/#general-placeholders).

The only relevant parameters that I can see would be the `PKG_VERSION` at build time and the `ENV_NAME` at install time, e.g. `Spyder-__PKG_VERSION__-{{ ENV_NAME }}`. For our installer this would result in `Spyder-6.0.0-spyder-runtime`. Personally, I think this is undesirable for our installers, but acceptable for shortcuts to standard conda environments.

I would propose that we reserve `Spyder` as the shortcut name for the one created from our installer environment, and use `Spyder-<ver>-<env name>` for standard environments. I think we could accomplish this with a post-link script in Spyder's conda package. This script  would modify `spyder-menu.json` appropriately after the package is installed, but before `menuinst` is executed, and only for our installer environment.
