### ISSUE TITLE
File explorer enhancements

### ISSUE THREAD

**Issue by penenkel** [spyder-ide/spyder#2406]
# Description

I have some suggestions on how to enhance the spyder file explorer panel:

At the moment if a file-type/content is supported by the spyder editor, it has an context action "Edit", otherwise it has the somewhat ubiquitous entry "Open" which delegates to the OS. This also results in folders having an "Open" command that opens the OS file explorer at that position.

I came up with these ideas, after trying to delete multiple files at once from within spyder. Which apparently is not possible because a) there is no multiselection+delete b) I could not easily switch to the OS file explorer and delete them there.
# Todo

I would propose
- [ ] an dedicated context menu entry for "open in OS file explorer" common to both files and folders.
- [ ] a "open via OS" action, i.e. allow the OS to determine what program to use to open the file.
- [ ] remove "Open" on folders ~~(or change its function to actually opening it in the spyder file 
  explorer, i.e. same as double-click action)~~
- [ ] Add multiselection (i.e. Ctrl/Shift+Click) and enable the (appropriate?) context menu actions to work on that selection. 
- [ ] remove "global" options from context menu. Move them to panel options menu instead.

**Comment by goanpeca** [comment]
@penenkel I think this is a good suggestion.

Do you have any other thoughts?

**Comment by penenkel** [comment]
hm, perhaps remove all "global" options from the context-menu and put them in the panel menu instead (most of them are already there). In my opinion context menus should only contain actions that pertain directly to the selected file/folder. Global options like the file filter, the font settings, the show all files and the show icon and text options don't belong there.

Ideally one would mirror the OS menu, but that may be to much (both in scope as well as in difficulty).
I think an "open in OS explorer" (for both files an folders) and an additional "open with OS" (for files) would be sufficient.

**Comment by goanpeca** [comment]
Agree, from a UX perspective the global options should not be there!

**Comment by goanpeca** [comment]
The 4 options on the bottom of this menu should not be there at all

![image](https://cloud.githubusercontent.com/assets/3627835/11615320/50609b5a-9c2b-11e5-9000-64255b4e7702.png)

@Nodd, @ccordoba12 ?

**Comment by ccordoba12** [comment]
Agreed

**Comment by penenkel** [comment]
With the exception of "Font" all these options (and they are really options, not menu actions) are present in the panel menu
![unbenannt](https://cloud.githubusercontent.com/assets/7736404/11616180/28efecb0-9c76-11e5-8076-70926ab467b1.png)
I suggest simply adding the font option to there and removing all four of them from the context menu.

**Comment by goanpeca** [comment]
@penenkel yes, that is what we are doing :-)

**Comment by jonnyhsu** [comment]
Is anyone working on this? If not, I'll take it on.

**Comment by ccordoba12** [comment]
Nope, there's no one working on this. Please go ahead.
