### ISSUE TITLE
Adapt the Find in Files so results display is flat, like ACK

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2850]
# Example screenshot

![image](https://cloud.githubusercontent.com/assets/3627835/11611709/5bf2ca92-9ba9-11e5-872d-b188bfac6d74.png)
# Todo
- [ ] Make tree a flat structure
- [ ] Add toggling options
- [ ] Highlight matched words
