### ISSUE TITLE
Improve and expand shortcut support in the Editor

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7894]
- [x] Fix issues with builtin shortcuts (PR #7768)
- [ ] Add back and expand support for GNU Emacs command (Issue #7883)
- [ ] Clean and standardize the default Spyder shortcut set (Epic #7853)
- [ ] Add a way to enter a numeric argument for the commands like in Emacs
- [ ] Add a way to support multiple keybinds for a same shortcut
- [ ] Add a way to support different keyboard shortcut sets (Emacs, RStudio)
- [ ] Add a way to support the creation of custom keyboard shortcut sets
- [ ] Add a way to unbind keybinds from a shortcut
- [ ] Add a way to swap a keybind from one shortcut to another more easily

**Comment by jnsebgosselin** [comment]
@ccordoba12 I would like to bring the same features we have for syntax coloring to the keyboard shortcut preferences.

Could you help me to determine the best way to modify the `spyder/config/main.py` to achieve that? Once this is set, I think implementing the rest will be fairly easy.

Then, we will be able to finish PR #2670

**Comment by jnsebgosselin** [comment]
Thanks Carlos. I'll try to implement that.

Is this going to cause backward compatibility issue with Spyder 3.x?

**Comment by jnsebgosselin** [comment]
Also would you like to support custom keyboard shortcut schemes? Like we do for syntax coloring?

**Comment by ccordoba12** [comment]
> Is this going to cause backward compatibility issue with Spyder 3.x?

Yep, and I haven't thought about it. To ease the transition, we need to associate the current `shortcuts` dict with the future `shortcuts_spyder`.

> Also would you like to support custom keyboard shortcut schemes? Like we do for syntax coloring?

That's a good idea too but I'd prefer to see shortcut sets implemented first before considering it.

**Comment by nerdfever** [comment]
Multiple keybinds for the same shortcut is important.

**Comment by pyZerrenner** [comment]
> Multiple keybinds for the same shortcut is important.

I second that. 

I actually mistook the current way (Spyder4.0.1) of entering sequences of keys as a way to enter multiple separate shortcuts.

**Comment by bjoseru** [comment]
So, four years in, and the main issue still open, what do people use to actually switch to Emacs keybindings? Is there a viable workaround yet?

**Comment by ccordoba12** [comment]
Sorry but stabilizing the LSP support in Spyder 4 (a year and a half) and then the new API we added in Spyder 5 (another year and a half) has taken most of our time (besides, of course, addressing bugs and making releases).

And there's no workaround to use Emacs keybindings at the moment. Sorry about that too.

**Comment by GitKia1392** [comment]
@bjoseru ikr
