### ISSUE TITLE
Improvements to the Ouline Explorer

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7971]
- [ ] Order of files in the Outline Explorer should be synced with the order of the files in its corresponding EditorStack.
- [ ] Add an option to alphabetize the order of the files.
- [ ] Add an option to show the root file item of files that are not Python files.
- [ ] Add a way to highlight the currently focused file as suggested in https://github.com/spyder-ide/spyder/pull/7962#issuecomment-425751960

**Comment by jnsebgosselin** [comment]
https://github.com/spyder-ide/spyder/pull/7968#discussion_r221500554 by @CAM-Gerlach:

> Of course, the outline explorer is still ordered alphabetically, rather than the order of the tabs in the Editor. Presumably out of scope for now, but if/when you make that change, if would be nice to have the option to either alphabetize it or make it follow the order of the editor, since both could potentially be useful depending on one's workflow.

> Also, to note, the outline explorer only show Python files, so it isn't a true file switcher for more general cases. Perhaps, as a longer-term idea, we could have an option to show them (just the files without the outlines, of course).

**Comment by jnsebgosselin** [comment]
https://github.com/spyder-ide/spyder/pull/7962#issuecomment-425751960 by @ccordoba12 :


My recommendation is to highlight the current file and class/method/cell/function by making the selected element to have a different background color, like VSCode does:

![seleccion_015](https://user-images.githubusercontent.com/365293/46262699-7f1f5d80-c4ca-11e8-9b58-48eaae75673a.png)

**Comment by ccordoba12** [comment]
I'd also like to add another suggestion here: Add a fuzzy search widget to filter by file names.

**Comment by bcolsen** [comment]
@jnsebgosselin 

I found two more that would/could be solved here.

#1986 and #2549

And if this is meant to be a "catch all" issue maybe #7976

**Comment by CAM-Gerlach** [comment]
@jnsebgosselin Maybe parts of PR #9384 would be useful to adapt for the outline explorer fuzzy search, e.g. the widget itself and the fuzzing code? Perhaps even use unified fuzzing code across our various fuzzy searches (variable explorer, outline, file switcher, completion of possible, etc.)?

**Comment by oscargus** [comment]
Unambiguous filenames:
![Screenshot from 2019-07-31 14-03-07](https://user-images.githubusercontent.com/8114497/62210303-1cbe1480-b39c-11e9-8042-8ae47b46e5b6.png)
